"use client";
import { useState, useMemo, useCallback } from "react";
const C={bg:"#FAFAF7",card:"#FFFFFF",warm:"#F4F1EB",cream:"#FBF9F5",text:"#1C1C30",mid:"#3E3E56",lt:"#6E6E82",faint:"#A0A0B0",pri:"#7851A9",priDk:"#5C3D8F",priLt:"#9B7EC8",priBg:"#F3EEFA",teal:"#0E9577",navy:"#1E3A5F",coral:"#E05535",emerald:"#2A8C5A",amber:"#D4930D",plum:"#8B3A8B",slate:"#3F6B7A",rose:"#C93B6B",olive:"#5A7F2A",indigo:"#4338CA",border:"#E5E2D9",borderLt:"#EEEAE2",sh:"0 1px 3px rgba(28,28,48,.04),0 5px 15px rgba(28,28,48,.03)",shH:"0 2px 8px rgba(28,28,48,.07),0 12px 32px rgba(28,28,48,.05)"};
const LEVELS=["Entry","Early-Career","Mid-Career","Senior","Leadership"];
const LC=[C.teal,C.navy,C.coral,C.plum,C.amber];
const SN=["Think Tank","Government","Dev Consulting","NGO / Civil Society","Corporate GAPA","Policy Communication","Multilateral / IO","Philanthropy / CSR","Legal & Regulatory","Social Enterprise","Academia","Political Strategy"];
const SC={"Think Tank":C.pri,"Government":C.navy,"Dev Consulting":C.coral,"NGO / Civil Society":C.emerald,"Corporate GAPA":C.plum,"Policy Communication":C.amber,"Multilateral / IO":C.slate,"Philanthropy / CSR":C.rose,"Legal & Regulatory":C.indigo,"Social Enterprise":C.coral,"Academia":C.teal,"Political Strategy":C.navy};
const PPILogo=({size=32})=>(<svg width={size} height={size} viewBox="0 0 40 40" fill="none"><rect width="40" height="40" rx="10" fill="url(#lg)"/><defs><linearGradient id="lg" x1="0" y1="0" x2="40" y2="40"><stop stopColor="#7851A9"/><stop offset="1" stopColor="#2D1B4E"/></linearGradient></defs><text x="8" y="28" fontFamily="sans-serif" fontWeight="800" fontSize="22" fill="white">P</text></svg>);

const R=[{id:1,title:"Research Intern",space:"Think Tank",level:0,salary:"₹5–15K/mo (stipend)",desc:"Support senior researchers with literature reviews, data collection, and citation management at institutions like CEEW, CPR, or ORF. First exposure to the policy research cycle. Typically 2–6 months. Despite low pay, these internships are competitive and offer genuine mentorship.",skills:["Literature review", "Data entry & cleaning", "Citation management", "Basic Excel", "Academic writing", "Library/database navigation"],orgs:["CEEW", "CPR", "ORF", "Vidhi", "NIPFP", "ICRIER", "Brookings India"],req:"Undergraduate or Master's student. Strong writing sample. Interest in a specific policy vertical.",next:[2, 3],verticals:["Any sector"]},
{id:2,title:"Research Analyst",space:"Think Tank",level:0,salary:"₹4–8 LPA (approx.)",desc:"Conduct primary and secondary research under guidance. Clean datasets, run quantitative analysis in Stata or R, draft working paper sections and policy briefs. At CEEW (200+ employees, ranked 1st in South Asia), hiring includes written test, research presentation, and interviews. First full-time policy role for many graduates.",skills:["Stata/R basics", "Policy brief drafting", "Data cleaning & analysis", "Qualitative coding", "Presentation design", "Secondary research"],orgs:["CEEW", "ICRIER", "Brookings India", "Carnegie India", "CSEP", "NCAER", "TERI", "Gateway House"],req:"Master's preferred. 0–2 years. Writing sample + quantitative test typical.",next:[3, 4, 58],verticals:["Climate", "Digital", "Health", "Finance", "Governance"]},
{id:3,title:"Programme Associate",space:"Think Tank",level:1,salary:"₹7–12 LPA (approx.)",desc:"Manage research programmes end-to-end: coordinate with funders, organise stakeholder consultations, manage timelines and deliverables, contribute to research outputs. Hybrid research-plus-management role. Essential glue.",skills:["Project management", "Grant reporting", "Stakeholder engagement", "Event management", "Budget tracking", "Report writing", "Donor communication"],orgs:["ORF", "TERI", "IIHS", "Takshashila", "Gateway House", "CUTS International"],req:"2–4 years experience. Ability to manage multiple workstreams.",next:[4, 5],verticals:["Any sector"]},
{id:4,title:"Fellow / Senior Researcher",space:"Think Tank",level:2,salary:"₹12–22 LPA (approx.)",desc:"Lead research projects independently. Author working papers. Present at government consultations and parliamentary committee meetings. Engage with media (op-eds, TV panels). Building a public profile and citation record. Supervise 2–4 junior researchers.",skills:["Independent research design", "Academic publishing", "Media engagement", "Advanced quantitative analysis", "Stakeholder consultation", "Team supervision", "Fundraising support"],orgs:["CPR", "CEEW", "ICRIER", "Vidhi", "MP-IDSA", "NIPFP", "CSEP"],req:"5–10 years. Published work. Master's/PhD preferred. Deep vertical expertise.",next:[5, 6],verticals:["Climate", "Governance", "Digital", "Trade", "Health"]},
{id:5,title:"Senior Fellow / Director",space:"Think Tank",level:3,salary:"₹22–40 LPA (approx.)",desc:"Shape the research agenda. Manage teams of 5–15. Represent the institution in high-level government consultations and international conferences. A recognised voice in your domain.",skills:["Research leadership", "Team management", "Fundraising & donor management", "Public intellectual presence", "Cross-sector convening", "Board presentations"],orgs:["CPR", "CEEW", "ORF", "ICRIER", "CSEP", "IIHS"],req:"10+ years. Strong publication record. Extensive network.",next:[6],verticals:["Any sector"]},
{id:6,title:"CEO / Director-General",space:"Think Tank",level:4,salary:"₹40–80+ LPA (approx.)",desc:"Lead the entire institution. Strategic direction, Board relations, fundraise at scale (₹20–50+ crore annual budgets), national and international representation.",skills:["Institutional leadership", "Board governance", "Strategic fundraising", "National representation", "Organisational development"],orgs:["CEEW", "CPR", "ORF", "ICRIER", "TERI"],req:"15+ years. National reputation. Extensive donor network.",next:[],verticals:["Any sector"]},
{id:7,title:"Health Policy Researcher",space:"Think Tank",level:1,salary:"₹7–14 LPA (approx.)",desc:"Specialised research on health systems, disease surveillance, nutrition, SRHR, or Ayushman Bharat. Combines epidemiological methods with policy analysis. Growing demand post-COVID.",skills:["Health systems analysis", "Epidemiological methods", "NFHS/HMIS data", "Public health writing", "Statistical analysis", "Qualitative health research"],orgs:["CEEW", "PHFI", "IIPS", "George Institute India", "IIHMR", "Accountability Initiative (CPR)"],req:"MPH, MA Development, or related. Understanding of NHM, Ayushman Bharat.",next:[4],verticals:["Health"]},
{id:8,title:"LAMP / Parliamentary Fellow",space:"Government",level:0,salary:"₹23K/mo (LAMP)",desc:"Work with a Member of Parliament for 10–11 months. Draft parliamentary questions, prepare speeches, research legislative issues. LAMP: ~40/year from 10,000+ applicants. Mukherjee Fellowship offers political strategy focus.",skills:["Legislative research", "Parliamentary procedure", "Brief writing for MPs", "Rapid synthesis", "Drafting parliamentary questions"],orgs:["PRS Legislative Research (LAMP)", "PPGF (Mukherjee)"],req:"Graduate degree. Typically under 26. Multi-stage selection.",next:[9, 10, 11, 32],verticals:["Governance"]},
{id:9,title:"CM Fellow / Good Governance Associate",space:"Government",level:0,salary:"₹30K–1.5L/mo (varies)",desc:"Posted to district administration in partnership with state governments. Scheme implementation, data-driven governance, field-level problem-solving. Gujarat (2009), Haryana CMGGA (2016), Maharashtra, Bihar (2026, IIM BG at ₹80K–1.5L/mo), Chhattisgarh. 8+ states.",skills:["District governance", "Data analysis", "Field research", "Govt scheme knowledge", "Presenting to bureaucrats"],orgs:["Haryana CMGGA", "Maharashtra CM Fellowship", "Bihar CM Fellowship", "Gujarat", "Chhattisgarh"],req:"Graduate/postgraduate. Age and domicile vary by state. 1–3 year commitment.",next:[10, 11, 21],verticals:["Governance", "Education", "Health", "Rural"]},
{id:10,title:"Young Professional (NITI Aayog)",space:"Government",level:1,salary:"~₹8.4 LPA (₹70K/mo)",desc:"Two-year contract at India's apex policy body. Support verticals like health, education, SDGs, infrastructure. Secretary-level meetings and PM-chaired sessions. Knowledge loss when contract expires.",skills:["Policy analysis", "Government file systems", "Data presentation", "Inter-ministerial coordination", "Note drafting"],orgs:["NITI Aayog"],req:"Under 30 typically. Master's preferred. Highly competitive.",next:[11, 16, 32],verticals:["Any sector"]},
{id:11,title:"Consultant (Govt Contract)",space:"Government",level:2,salary:"₹12–25 LPA (approx.)",desc:"Contractual domain expert in ministries or state govts, often funded by World Bank, UNDP, or bilateral agencies. Bring specific technical expertise the permanent bureaucracy lacks. 11 months to 3 years.",skills:["Deep domain expertise", "Policy drafting", "Government processes", "Report writing (govt style)", "Stakeholder management"],orgs:["Central ministries", "State govts", "World Bank projects", "UNDP programmes"],req:"5–10 years domain experience. Specific technical skills.",next:[12],verticals:["Any sector"]},
{id:12,title:"IAS / Senior Civil Servant",space:"Government",level:3,salary:"₹15–30 LPA + benefits (approx.)",desc:"Career civil servant via UPSC. SDM → DM → Commissioner → Secretary. A DM oversees virtually every scheme across India's 741 districts. Extraordinary power and scale.",skills:["Administrative leadership", "Political navigation", "Crisis management", "File noting mastery", "Hindi/regional language"],orgs:["All central and state government positions"],req:"UPSC Civil Services (10L+ registrations, ~1,000 seats). 2–4 years prep.",next:[],verticals:["Any sector"]},
{id:13,title:"Technology Policy Officer (Govt)",space:"Government",level:1,salary:"₹8–18 LPA (approx.)",desc:"Digital governance, AI policy, DPDP Act implementation, cybersecurity frameworks within MeitY, IT ministries, or state IT departments. Rapidly growing as India builds AI governance frameworks.",skills:["Digital policy understanding", "DPDP Act/IT Act knowledge", "AI governance frameworks", "Data protection compliance", "Technical-to-policy translation"],orgs:["MeitY", "State IT depts", "NITI Aayog (digital)", "Data Protection Board", "CERT-In"],req:"Tech + policy or policy + tech fluency. Understanding of India's DPI stack.",next:[11],verticals:["Digital"]},
{id:14,title:"Analyst / Research Analyst",space:"Dev Consulting",level:0,salary:"₹5–10 LPA (approx.)",desc:"Entry-level. Secondary research, Excel models, slides, support senior consultants. Learn the consulting rhythm: scoping, research, analysis, synthesis, presentation.",skills:["Secondary research", "Excel modelling", "Slide design", "MECE thinking", "Client communication", "Data compilation"],orgs:["Sattva", "Samagra", "Samhita", "Think Through", "Access Livelihoods", "Athena Infonomics"],req:"Bachelor's or Master's. Analytical aptitude. Case interview typical.",next:[15, 16],verticals:["Any sector"]},
{id:15,title:"Associate / Senior Associate",space:"Dev Consulting",level:1,salary:"₹10–22 LPA (approx.)",desc:"Own workstreams. Lead primary research (FGDs, KIIs, surveys). Present to mid-level clients. At Dalberg (750+ people, 30 offices), Associates typically have MPP/MBA backgrounds.",skills:["Primary research design", "FGD/KII facilitation", "Data analysis", "Client management", "Proposal writing", "Sector expertise"],orgs:["Dalberg", "FSG", "IDinsight", "Sattva", "IPE Global", "BCG Social Impact", "Bridgespan"],req:"2–5 years. MPP/MBA or strong consulting background.",next:[16, 17],verticals:["Any sector"]},
{id:16,title:"Manager / Engagement Manager",space:"Dev Consulting",level:2,salary:"₹18–35 LPA (approx.)",desc:"Manage entire engagements. Lead teams of 3–6. Shape methodology, ensure quality, present to Principal Secretaries and Foundation heads. Beginning business development.",skills:["Engagement management", "Team leadership", "Quality assurance", "Senior client relations", "Business development", "Methodology design"],orgs:["Dalberg", "FSG", "Deloitte GPS", "McKinsey Social Sector", "PwC", "KPMG Dev Advisory"],req:"5–10 years. Track record. Sector depth.",next:[17],verticals:["Any sector"]},
{id:17,title:"Principal / Partner",space:"Dev Consulting",level:4,salary:"₹40–80+ LPA (approx.)",desc:"Drive business development, shape firm strategy, lead thought leadership. P&L responsibility. Deep institutional relationships.",skills:["Business development", "Thought leadership", "P&L management", "Institutional relationships", "Strategic advisory"],orgs:["Dalberg", "FSG", "Bridgespan", "Deloitte GPS", "McKinsey"],req:"12+ years. Revenue generation track record.",next:[],verticals:["Any sector"]},
{id:18,title:"Climate / Sustainability Consultant",space:"Dev Consulting",level:1,salary:"₹10–22 LPA (approx.)",desc:"Climate finance, carbon markets, just transition, renewable energy policy, ESG strategy. Rapidly growing as India pursues Net Zero 2070.",skills:["Climate policy frameworks", "Carbon accounting", "ESG analysis", "Renewable energy economics", "NDC analysis", "Climate finance"],orgs:["Dalberg", "CEEW", "WRI India", "TERI", "EY Climate", "Deloitte Sustainability", "CPI India"],req:"Climate science, environmental economics, or sustainability background. 2–5 years.",next:[16],verticals:["Climate"]},
{id:19,title:"M&E / Impact Evaluation Specialist",space:"Dev Consulting",level:2,salary:"₹14–28 LPA (approx.)",desc:"Design and implement evaluation frameworks. RCTs, quasi-experimental designs, theory-based evaluations. Growing demand for evidence of impact.",skills:["RCT design", "Stata/R (advanced)", "Survey design", "Theory of change", "Mixed-methods research", "Impact measurement (IRIS+)"],orgs:["IDinsight", "J-PAL South Asia", "3ie", "IFMR/Krea", "World Bank (evaluation)"],req:"Master's/PhD with quantitative methods. Statistical programming. Field research experience.",next:[],verticals:["Any sector"]},
{id:20,title:"Field Coordinator",space:"NGO / Civil Society",level:0,salary:"₹2.5–5 LPA (approx.)",desc:"Work in villages, blocks, or urban slums. Mobilise communities, collect household data, support programme delivery. Most ground-level role. Local language non-negotiable.",skills:["Community mobilisation", "Local language fluency", "Data collection", "SHG facilitation", "RTI awareness", "Govt scheme knowledge", "Conflict resolution"],orgs:["PRADAN", "Jan Sahas", "Gram Vaani", "SEWA", "Action Aid", "Childline India"],req:"Bachelor's. Local language essential. Willingness to live in rural areas.",next:[21, 22],verticals:["Rural", "Gender", "Health", "Education", "Water"]},
{id:21,title:"Programme Manager",space:"NGO / Civil Society",level:1,salary:"₹6–12 LPA (approx.)",desc:"Manage programme across 5–20 blocks/districts. Supervise 10–30 staff. Track outcomes, manage budgets (₹20L–₹2Cr), report to donors. Bridge between ground reality and institutional expectations.",skills:["Programme design", "Team supervision", "M&E and MIS", "Budget management", "Donor reporting", "Training of trainers"],orgs:["Pratham", "Akshara", "WaterAid", "Room to Read", "TFI", "Azim Premji Foundation", "The/Nudge"],req:"3–6 years field experience. Master's in social work or development valued.",next:[22, 23, 26],verticals:["Education", "Health", "Rural", "Water", "Gender"]},
{id:22,title:"State / Regional Director",space:"NGO / Civil Society",level:2,salary:"₹12–22 LPA (approx.)",desc:"Oversee all programmes in a state/region. Manage 20–100+ staff. State govt relationships at Principal Secretary level. Lead fundraising.",skills:["Strategic leadership", "State govt relations", "Large team management", "Fundraising", "Advocacy", "Context expertise"],orgs:["Pratham", "Oxfam India", "CRY", "HelpAge", "The/Nudge", "Catalyst Group"],req:"8–12 years including field. Deep state networks. Scale-up track record.",next:[23],verticals:["Any sector"]},
{id:23,title:"CEO / Executive Director",space:"NGO / Civil Society",level:4,salary:"₹20–50+ LPA (approx.)",desc:"Lead the entire organisation. Board relations, national fundraising (₹10–100+ crore budgets), public representation. FCRA crackdown has made this significantly more complex.",skills:["Organisational leadership", "Board governance", "National fundraising", "Public communication", "Sector thought leadership", "FCRA compliance"],orgs:["Pratham", "SEWA", "Dasra", "Ashoka India"],req:"15+ years. National reputation.",next:[],verticals:["Any sector"]},
{id:24,title:"SRHR / Gender Policy Specialist",space:"NGO / Civil Society",level:1,salary:"₹6–14 LPA (approx.)",desc:"Sexual and reproductive health rights, gender-based violence prevention, women's empowerment policy. Combine policy analysis with community programme design.",skills:["Gender analysis frameworks", "SRHR policy knowledge", "Community engagement", "Advocacy strategy", "Qualitative research", "Programme design"],orgs:["CREA", "CommonHealth", "Nirantar", "IT for Change", "Oxfam India (gender)", "UN Women India"],req:"Gender studies, public health, or social work background.",next:[22],verticals:["Gender"]},
{id:25,title:"Public Health Programme Manager",space:"NGO / Civil Society",level:2,salary:"₹10–20 LPA (approx.)",desc:"Large-scale health programmes: POSHAN, disease surveillance, immunisation, maternal health. Interface between health policy and community delivery. Often Gates Foundation or USAID funded.",skills:["Health programme management", "NHM architecture", "Disease surveillance", "Nutrition programme design", "Health MIS", "Community health worker supervision"],orgs:["PHFI", "Swasti/Catalyst Group", "PATH India", "CHAI", "IPE Global (health)", "Jhpiego India"],req:"MPH or MD Community Medicine preferred. 5–8 years.",next:[22],verticals:["Health"]},
{id:26,title:"Fundraising / Development Manager",space:"NGO / Civil Society",level:2,salary:"₹10–20 LPA (approx.)",desc:"Institutional fundraising: proposals (CSR, bilateral, foundation), donor relationships, compliance (FCRA, 80G). Critical as FCRA shrinks and domestic philanthropy grows.",skills:["Proposal writing", "Donor management", "CSR engagement (Section 135)", "FCRA/80G compliance", "Impact reporting", "CRM tools"],orgs:["Any mid-to-large NGO", "Dasra", "GuideStar India"],req:"5+ years. Understanding of donor landscape. Excellent writing.",next:[43],verticals:["Any sector"]},
{id:27,title:"Policy Analyst (Corporate)",space:"Corporate GAPA",level:0,salary:"₹8–16 LPA (approx.)",desc:"Track legislative/regulatory developments. Draft monitoring reports, maintain regulatory trackers, support position papers. Track DPDP Rules, Telecom Act, intermediary guidelines, e-commerce rules.",skills:["Regulatory tracking", "Legislative analysis", "Report writing", "Stakeholder mapping", "Govt gazette monitoring"],orgs:["Google India", "Meta India", "Amazon India", "Uber", "Flipkart", "PhonePe", "Paytm"],req:"Law degree or MPP/MA. 0–2 years. Understanding of regulatory landscape.",next:[28],verticals:["Digital", "Finance", "Trade"]},
{id:28,title:"Policy Manager / Govt Affairs Manager",space:"Corporate GAPA",level:2,salary:"₹22–42 LPA (approx.)",desc:"Own a policy portfolio (data protection, competition law, content regulation). Draft position papers, engage Joint Secretary-level officials, coordinate with global teams. Google restructured India policy Feb 2025.",skills:["Position paper writing", "Government engagement", "Industry body coordination", "Cross-functional leadership", "Regulatory analysis", "Global coordination"],orgs:["Google", "Meta", "Amazon", "Microsoft", "Apple", "Netflix", "Mastercard", "Uber"],req:"5–8 years in policy, law, or government. Relationship network.",next:[29],verticals:["Digital", "Finance", "Trade", "Health"]},
{id:29,title:"Director, Public Policy",space:"Corporate GAPA",level:3,salary:"₹45–75 LPA (approx.)",desc:"Lead portfolio of policy issues for India. Manage team. Engage Addl Secretary/Secretary level. Company's face to Indian government.",skills:["Senior govt relations", "Strategic communications", "Team leadership", "Crisis management", "Regulatory strategy", "C-suite briefings"],orgs:["Google India", "Meta India", "Amazon India", "Reliance", "Tata Group", "Airtel"],req:"10–15 years. Extensive network. Political economy intuition.",next:[30],verticals:["Digital", "Trade"]},
{id:30,title:"VP / Head of Public Policy",space:"Corporate GAPA",level:4,salary:"₹80 LPA–₹1.5 Cr+ (approx.)",desc:"Most senior policy role at a major corporation. Shape entire government engagement strategy. Direct access to India CEO and global C-suite. Ministerial meetings.",skills:["Executive leadership", "Geopolitical intelligence", "Board communication", "Regulatory foresight", "Reputation management"],orgs:["Google", "Meta", "Amazon", "Microsoft", "Reliance", "Tata"],req:"15+ years. Deep institutional relationships. Political economy mastery.",next:[],verticals:["Digital", "Trade"]},
{id:31,title:"Industry Body Policy Lead",space:"Corporate GAPA",level:2,salary:"₹15–30 LPA (approx.)",desc:"Lead policy research and advocacy at NASSCOM, CII, FICCI, or IAMAI. Draft industry position papers, coordinate member consultations.",skills:["Industry advocacy", "Position paper drafting", "Member coordination", "Government consultation", "Sector research"],orgs:["NASSCOM", "CII", "FICCI", "IAMAI", "AMCHAM India", "US-India Business Council"],req:"5–8 years in policy, law, or industry relations.",next:[28],verticals:["Digital", "Finance", "Trade"]},
{id:32,title:"Content / Editorial Associate",space:"Policy Communication",level:0,salary:"₹4–8 LPA (approx.)",desc:"Write, edit, curate policy content for newsletters, social media, websites. At PPI: The Policy Post (22,000+ subscribers), 100+ opportunities/week, 60,000+ LinkedIn. At IDR (2,000+ articles): commissioning analytical pieces.",skills:["Editing & proofreading", "Social media management", "Newsletter tools", "SEO basics", "Content curation", "CMS management"],orgs:["IDR", "PPI", "IndiaSpend", "Down To Earth", "Mongabay India", "Youth Ki Awaaz"],req:"Strong writing portfolio. Policy landscape understanding. Digital comfort.",next:[33, 34],verticals:["Any sector"]},
{id:33,title:"Editor / Senior Editor",space:"Policy Communication",level:2,salary:"₹12–22 LPA (approx.)",desc:"Commission articles, manage editorial calendar, develop thematic series. Shape the publication's intellectual identity.",skills:["Commissioning", "Editorial strategy", "Expert network building", "Quality control", "Long-form editing", "Data viz direction"],orgs:["IDR", "IndiaSpend", "EPW", "Article 14", "Scroll", "The Wire", "Seminar"],req:"5–8 years in journalism or editorial. Strong contributor network.",next:[34],verticals:["Any sector"]},
{id:34,title:"Editor-in-Chief / Head of Content",space:"Policy Communication",level:3,salary:"₹20–35 LPA (approx.)",desc:"Set editorial direction for an entire platform. Manage team. Drive audience growth, engagement, and revenue strategy.",skills:["Editorial leadership", "Audience & revenue strategy", "Public speaking", "Partnership development", "Brand building", "Team management"],orgs:["IDR", "The Wire", "Scroll", "IndiaSpend", "PPI"],req:"10+ years. Established editorial reputation.",next:[],verticals:["Any sector"]},
{id:35,title:"Data Journalist",space:"Policy Communication",level:1,salary:"₹6–14 LPA (approx.)",desc:"Data-driven journalism on policy issues. At IndiaSpend, reach millions with stories backed by NSSO, NFHS data. Statistical skills meets narrative craft.",skills:["Data analysis (Python/R)", "Data visualisation (D3, Flourish)", "Statistical storytelling", "Govt data navigation", "SEO/audience analytics"],orgs:["IndiaSpend", "Factchecker.in", "IDR", "Down To Earth", "The Print"],req:"Quantitative skills + writing ability. Published data stories.",next:[33],verticals:["Any sector"]},
{id:36,title:"Consultant (UN / World Bank)",space:"Multilateral / IO",level:1,salary:"₹8–22 LPA (contract, approx.)",desc:"Short-term contracts (3–11 months). Most common foot-in-the-door. No benefits, no security, but excellent exposure. Many cycle through 3–5 contracts before converting.",skills:["Technical writing (UN style)", "Data analysis", "Log frame development", "Concept note drafting", "M&E basics"],orgs:["UNDP India", "UNICEF India", "World Bank", "WHO India", "FAO India", "ILO India", "UN Women"],req:"Master's degree. 2–5 years domain experience.",next:[37, 38, 40],verticals:["Health", "Education", "Climate", "Gender", "Governance"]},
{id:37,title:"National Professional Officer",space:"Multilateral / IO",level:2,salary:"₹18–35 LPA (approx.)",desc:"Full staff position in a UN agency's India office. Manage programme components, coordinate with government (Joint Secretary level). Country-specific (you stay in India).",skills:["Programme management", "Government coordination", "M&E frameworks", "Results-based management", "Technical expertise", "Budget management"],orgs:["UNDP India", "UNICEF India", "WHO India", "ILO India", "UN Women", "UNFPA"],req:"5–10 years. Domain expertise. Often recruited from consultant pool.",next:[38, 39],verticals:["Health", "Education", "Climate", "Gender"]},
{id:38,title:"International Professional (P-3/P-4)",space:"Multilateral / IO",level:3,salary:"₹35–60 LPA (approx.)",desc:"International staff grade, posted globally. Lead programme design, manage large teams, represent agency in high-level dialogues. Hundreds of applicants per position.",skills:["Strategic programme leadership", "Diplomatic engagement", "Cross-country coordination", "Resource mobilisation", "Policy advocacy", "Team management"],orgs:["UNDP", "UNICEF", "WHO", "World Bank", "ADB", "ILO"],req:"8–15 years. International experience. PhD valued.",next:[39],verticals:["Any sector"]},
{id:39,title:"Country Representative",space:"Multilateral / IO",level:4,salary:"₹55–100+ LPA (approx.)",desc:"Lead an entire UN agency in a country. Multi-million dollar portfolios. Ministerial-level interface. Decades of experience required.",skills:["Country-level leadership", "Ministerial relations", "Portfolio management", "Diplomatic representation", "UN system coordination"],orgs:["UNDP", "UNICEF", "WHO", "FAO", "ILO"],req:"15+ years. Multiple country postings.",next:[],verticals:["Any sector"]},
{id:40,title:"Policy Comms Specialist (IO)",space:"Multilateral / IO",level:1,salary:"₹10–18 LPA (approx.)",desc:"Translate complex research into accessible formats. Policy briefs, infographics, short videos. Growing as every IO recognises the research-to-readership gap.",skills:["Policy writing (multiple formats)", "Data visualisation", "Infographic design", "Media engagement", "Social media strategy", "Plain language"],orgs:["UNDP India", "UNICEF India", "CEEW", "World Bank India"],req:"3–5 years in journalism, comms, or policy writing.",next:[33],verticals:["Any sector"]},
{id:41,title:"Programme Associate (Foundation)",space:"Philanthropy / CSR",level:0,salary:"₹6–10 LPA (approx.)",desc:"Support grant management: due diligence on grantees, monitor projects, compile portfolio reports. At Dasra, also produce sector landscape studies.",skills:["Due diligence", "Grant administration", "M&E basics", "Report compilation", "Sector research", "Excel/data"],orgs:["Tata Trusts", "EdelGive", "Dasra", "Rohini Nilekani Philanthropies", "CIFF India"],req:"Master's degree. 1–3 years in development. NGO landscape understanding.",next:[42, 43],verticals:["Any sector"]},
{id:42,title:"Programme Officer / CSR Manager",space:"Philanthropy / CSR",level:2,salary:"₹14–25 LPA (approx.)",desc:"Manage portfolio of grants/CSR (₹5–50Cr across 10–25 grantees). Site visits, impact assessment, thematic strategies. CSR (Section 135: ~₹35,000Cr/yr) increasingly requires this profile.",skills:["Portfolio management", "Impact assessment", "Grantee management", "Sector mapping", "Theory of change", "Board presentations"],orgs:["Tata Trusts", "Azim Premji Foundation", "Infosys Foundation", "Piramal Foundation", "Godrej CSR", "Wipro Foundation"],req:"5–8 years. Deep sector knowledge.",next:[43],verticals:["Education", "Health", "Rural", "Climate", "Gender"]},
{id:43,title:"Director / Head of Programmes",space:"Philanthropy / CSR",level:3,salary:"₹28–55+ LPA (approx.)",desc:"Shape entire grantmaking/CSR strategy. Team of programme officers. Board presentations. Landscape studies determining where hundreds of crores get deployed.",skills:["Strategic grantmaking", "Board governance", "Team leadership", "Sector thought leadership", "Blended finance", "Systems thinking"],orgs:["Tata Trusts", "Azim Premji Foundation", "Rohini Nilekani Philanthropies", "CIFF India", "Omidyar Network"],req:"12+ years. National reputation. Deep ecosystem networks.",next:[],verticals:["Any sector"]},
{id:44,title:"Impact Investing Associate",space:"Philanthropy / CSR",level:1,salary:"₹10–18 LPA (approx.)",desc:"Source deals, due diligence on social enterprises, financial models, investment committee memos. At Aavishkaar, evaluate enterprises across agriculture, financial inclusion, essential services.",skills:["Financial modelling", "Due diligence", "Market research", "Impact measurement (IRIS+)", "Investment memo writing", "Sector analysis"],orgs:["Aavishkaar Capital", "Omidyar Network India", "Acumen India", "Unitus Capital", "Caspian Debt"],req:"MBA/CFA or strong finance background. Development sector interest.",next:[43],verticals:["Finance", "Education", "Health", "Climate"]},
{id:45,title:"Legal Research Associate",space:"Legal & Regulatory",level:0,salary:"₹4–9 LPA (approx.)",desc:"Research case law, draft briefs, support PILs or regulatory filings. At Vidhi: deep legal analysis feeding legislative recommendations. At IFF: digital rights.",skills:["Legal research", "Case brief drafting", "Regulatory tracking", "Legal writing", "Constitutional law"],orgs:["Vidhi", "CLPR", "HRLN", "Internet Freedom Foundation", "SFLC.in", "PRS"],req:"LLB from recognised law school. Interest in public interest law.",next:[46, 47],verticals:["Digital", "Governance", "Gender", "Climate"]},
{id:46,title:"Associate (Law Firm Policy Practice)",space:"Legal & Regulatory",level:1,salary:"₹10–20 LPA (approx.)",desc:"Top-tier firm's regulatory/policy practice. DPDP compliance, competition law, environmental clearances. Commercial legal practice meets policy.",skills:["Regulatory compliance advisory", "Client communication", "Legal drafting", "Sector regulation", "Stakeholder mapping"],orgs:["AZB & Partners", "Trilegal", "Cyril Amarchand", "Khaitan & Co", "Shardul Amarchand"],req:"LLB/LLM from top law school. 2–5 years. DPDP/competition/telecom specialisation.",next:[47, 28],verticals:["Digital", "Finance", "Climate"]},
{id:47,title:"Senior Researcher / Programme Lead",space:"Legal & Regulatory",level:2,salary:"₹14–25 LPA (approx.)",desc:"Lead research programme at legal policy org. Author reports influencing legislative drafting. Engage parliamentary committees and regulatory bodies.",skills:["Legislative analysis", "Report authorship", "Regulatory body engagement", "Parliamentary interaction", "Team management", "Public communication"],orgs:["Vidhi", "CLPR", "Internet Freedom Foundation", "Daksh", "PRS"],req:"5–10 years. Published legal-policy analysis. Regulatory body network.",next:[48],verticals:["Governance", "Digital", "Climate"]},
{id:48,title:"Director / Head of Practice",space:"Legal & Regulatory",level:3,salary:"₹25–50 LPA (approx.)",desc:"Lead entire practice area. Shape advocacy strategy. Supreme Court proceedings, parliamentary consultations, national media. Shaping legal architecture of Indian policymaking.",skills:["Practice leadership", "Strategic litigation", "Advocacy strategy", "Govt relations", "Public interest law"],orgs:["Vidhi", "CLPR", "HRLN", "Major law firms"],req:"10+ years. National reputation in legal-policy intersection.",next:[],verticals:["Governance", "Digital"]},
{id:49,title:"Environmental Lawyer / Policy Specialist",space:"Legal & Regulatory",level:1,salary:"₹8–16 LPA (approx.)",desc:"Environmental clearances, forest rights, climate litigation, pollution control, NGT cases. Combines environmental law with policy advocacy.",skills:["Environmental law (EPA, FRA, EIA)", "NGT procedures", "PIL drafting", "Climate litigation", "Forest rights", "Corporate environmental compliance"],orgs:["Vidhi (environment)", "LIFE", "CLPR", "CSE", "Environmental law firms"],req:"LLB with environmental law interest. EIA, Forest Rights Act understanding.",next:[47],verticals:["Climate"]},
{id:50,title:"Product Manager (GovTech)",space:"Social Enterprise",level:1,salary:"₹10–22 LPA (approx.)",desc:"Build tech products for governance: digital public goods, dashboards, citizen service platforms. At eGov Foundation, municipal platforms. At Haqdarshak, connecting citizens with schemes. Hybrid tech + policy.",skills:["Product management", "User research", "Agile methodology", "Govt procurement", "Design thinking", "Data systems"],orgs:["eGov Foundation", "EkStep", "Dimagi", "Haqdarshak", "Samagra (tech)", "OpenCity"],req:"Engineering/design + policy interest. 2–5 years in product. Govt context.",next:[51],verticals:["Digital", "Governance"]},
{id:51,title:"VP / Director (Social Enterprise)",space:"Social Enterprise",level:3,salary:"₹25–50 LPA (approx.)",desc:"Lead major programme or business unit at scaled social enterprise. Large teams, strategy, govt clients, investors. At CSF, influencing state education policy at scale.",skills:["Strategic leadership", "Govt client management", "Fundraising", "Scale-up strategy", "Team building", "Impact reporting"],orgs:["Central Square Foundation", "EkStep", "TechnoServe India", "Frontier Markets", "Avanti Fellows"],req:"10+ years. Track record of scaling.",next:[],verticals:["Education", "Health", "Digital", "Rural"]},
{id:52,title:"AI Policy Researcher",space:"Social Enterprise",level:1,salary:"₹8–18 LPA (approx.)",desc:"AI governance frameworks, algorithmic bias, responsible AI deployment, AI for development. Rapidly emerging as India develops AI regulatory approach. May sit in think tanks, GovTech firms, or consultancies.",skills:["AI/ML understanding", "AI governance frameworks", "Responsible AI principles", "Policy analysis", "Technical writing", "Comparative regulatory analysis"],orgs:["Vidhi (AI)", "IT for Change", "iSPIRT", "NASSCOM (AI)", "Google India (AI policy)", "Microsoft India"],req:"Tech + policy or policy + genuine AI understanding. Interdisciplinary thinking.",next:[28, 47],verticals:["Digital"]},
{id:53,title:"Teaching Fellow / Asst Professor",space:"Academia",level:1,salary:"₹6–16 LPA (approx.)",desc:"Teach policy courses at India's growing policy programmes (16–18 dedicated per Phadnis, Ayyangar & Pellissery 2024). Shape next generation.",skills:["Curriculum design", "Classroom teaching", "Research methodology", "Publication", "Student mentoring"],orgs:["JSGP", "Azim Premji University", "Ashoka", "TISS", "IIT Delhi SPP", "NLSIU", "Kautilya", "IIM Bangalore"],req:"PhD or ABD. Publication record. Teaching experience.",next:[54],verticals:["Any sector"]},
{id:54,title:"Associate / Full Professor",space:"Academia",level:3,salary:"₹18–40 LPA (approx.)",desc:"Tenured faculty. Shape curriculum, supervise PhDs, contribute to national discourse. Senior faculty serve on government advisory boards.",skills:["Advanced research", "PhD supervision", "Grant acquisition", "Public intellectual presence", "Curriculum leadership", "Policy advisory"],orgs:["JNU", "JSGP", "Ashoka", "IIM Bangalore", "TISS", "APU", "NLSIU"],req:"PhD. 8+ years. Strong journal publication record.",next:[],verticals:["Any sector"]},
{id:55,title:"Political Research Associate",space:"Political Strategy",level:0,salary:"₹4–8 LPA (approx.)",desc:"Electoral data, talking points, constituency briefings. Less visible but growing. Mukherjee Fellowship trains for this intersection.",skills:["Electoral data analysis", "Brief writing", "Political communication", "Constituency research", "Media monitoring", "Social media analytics"],orgs:["PPGF", "I-PAC", "Political consultancies", "MP/MLA offices"],req:"Understanding of Indian political landscape. Data and writing skills.",next:[56, 57],verticals:["Governance"]},
{id:56,title:"Political Strategy Consultant",space:"Political Strategy",level:2,salary:"₹12–28 LPA (approx.)",desc:"Advise on policy positioning, governance delivery, campaign strategy. At I-PAC, data-driven election campaigns.",skills:["Political communication", "Campaign strategy", "Governance advisory", "Media strategy", "Data-driven decisions"],orgs:["I-PAC", "Political consultancies", "Party strategy teams"],req:"5–8 years in policy or politics.",next:[57],verticals:["Governance"]},
{id:57,title:"Chief of Staff / Senior Advisor",space:"Political Strategy",level:3,salary:"₹22–55+ LPA (approx.)",desc:"Advise senior elected official. Coordinate political office and bureaucracy. Rare, high-influence. Almost never openly advertised.",skills:["Political judgment", "Bureaucratic coordination", "Crisis management", "Policy synthesis", "Confidential counsel"],orgs:["CMO offices", "PMO", "Senior MP offices"],req:"10+ years. Deep political networks. Trust of the principal.",next:[],verticals:["Governance"]},
{id:58,title:"Data Analyst / Data for Policy",space:"Think Tank",level:1,salary:"₹7–16 LPA (approx.)",desc:"Build datasets, clean admin data (NSSO, NFHS, ASI), create visualisations, run statistical models. Growing demand for evidence-based policymaking.",skills:["Python/R programming", "SQL", "Data visualisation (Tableau, D3)", "Statistical analysis", "Govt data (NSSO, NFHS, Census)", "Survey data", "Web scraping"],orgs:["CEEW", "IDinsight", "IndiaSpend", "J-PAL", "World Bank", "NITI Aayog"],req:"Quantitative degree. Strong programming. Policy interest.",next:[19],verticals:["Any sector"]},
{id:59,title:"Community Manager / Chapter Lead",space:"Policy Communication",level:0,salary:"₹3–7 LPA (approx.)",desc:"Build and manage local policy communities: meetups, opportunities, discussions. PPI runs 34 city chapters. Community management is increasingly professional.",skills:["Community building", "Event management", "Social media", "Content curation", "Local networking", "WhatsApp group management"],orgs:["PPI", "IDR", "Think tank outreach teams", "University policy clubs"],req:"Passion for policy. Local network. Communication skills.",next:[32],verticals:["Any sector"]},
{id:60,title:"Nutrition Policy Specialist",space:"NGO / Civil Society",level:2,salary:"₹10–20 LPA (approx.)",desc:"POSHAN Abhiyaan, ICDS reform, maternal and child nutrition, fortification policy. India's NFHS-5 shows 35.5% stunting among under-5s: a critical and growing field.",skills:["Nutrition science", "POSHAN/ICDS knowledge", "M&E for nutrition", "Community nutrition assessment", "Policy analysis", "Government health architecture"],orgs:["Alive & Thrive India", "UNICEF India (nutrition)", "Tata Trusts (nutrition)", "Gates Foundation", "NITI Aayog (nutrition)"],req:"Nutrition, public health, or food policy background. ICDS/POSHAN architecture understanding.",next:[25],verticals:["Health"]}];

const SK=[
{cat:"Research & Analysis",c:C.pri,skills:["Quantitative analysis (Stata/R/Python)","Qualitative research (FGDs, KIIs, ethnography)","Policy brief writing (1–4 pagers)","Literature review & evidence synthesis","Data visualisation (Tableau, D3, Power BI)","Survey design & sampling","Cost-benefit analysis","GIS / spatial analysis","Impact evaluation (RCTs, DiD, RDD)","Econometrics & statistical modelling","Systematic reviews & meta-analysis","Budget & public expenditure analysis","Political economy analysis"]},
{cat:"Communication & Writing",c:C.coral,skills:["Op-ed & commentary writing","Donor/government report writing","Slide deck storytelling","Newsletter & content strategy","Social media for policy advocacy","Speechwriting & talking points","Translation (English to Hindi/regional)","Podcast & video scripting","Data journalism","Infographic design","Plain language for public audiences","Press release writing","Academic journal writing"]},
{cat:"Technical & Digital",c:C.indigo,skills:["Python / R / Stata programming","Web scraping & data collection","Dashboard development","RTI & NIC systems navigation","DPI (Aadhaar, UPI, DigiLocker)","AI/ML for policy applications","GovTech platform design","Cybersecurity policy awareness","SQL & database management","Project management tools (Jira)","CRM & community tools","Advanced Excel (pivot, VBA)","GIS mapping (QGIS, ArcGIS)"]},
{cat:"Interpersonal & Leadership",c:C.emerald,skills:["Stakeholder mapping & engagement","Cross-cultural communication","Negotiation & conflict resolution","Team management & mentoring","Public speaking & facilitation","Coalition & network building","Political economy sensing","Building trust with bureaucrats","Managing up","Crisis communication","Emotional intelligence","Working across ideological lines","Donor relationship management"]},
{cat:"Domain & Sector",c:C.amber,skills:["Constitutional & admin law","Budget processes (Union/state)","Legislative process (Parliament)","DPDP Act & data protection","AI governance & platform regulation","NHM / Ayushman Bharat","Climate (NDC, Paris, Net Zero)","FCRA / CSR (Section 135)","Indian federalism","Govt scheme architecture","SDGs & international frameworks","Land & property rights","EIA process"]},
{cat:"Management & Operations",c:C.plum,skills:["Programme / project management","M&E framework design","Grant writing & proposals","Budget & financial reporting","Procurement & compliance","Theory of change development","Risk management","Strategic planning & OKRs","HR in nonprofits","Organisational development","Knowledge management","Board governance & reporting","FCRA / 80G compliance"]},
];

const PA=[
{n:"LAMP Fellowship (PRS)",d:"~40/yr with MPs. \u20b923K/mo. 10\u201311 months. Since 2010.",t:"fellowship"},
{n:"Mukherjee Fellowship",d:"Policymaking + political strategy consulting with leading policymakers.",t:"fellowship"},
{n:"Haryana CMGGA",d:"Since 2016. 22 districts. 8+ cohorts. With Ashoka University.",t:"fellowship"},
{n:"Maharashtra CM Fellowship",d:"7th year. IIT Bombay partnership. District governance innovation.",t:"fellowship"},
{n:"Bihar CM Fellowship (IIM BG)",d:"Newest (2026). \u20b980K\u20131.5L/mo. 2-year. PG Certificate.",t:"fellowship"},
{n:"Gujarat / Chhattisgarh CM Fellowships",d:"Gujarat pioneered (2009). Chhattisgarh runs two variants. 8+ states total.",t:"fellowship"},
{n:"SBI Youth for India",d:"13-month rural immersion. \u20b920K/mo + accommodation. Grassroots NGOs.",t:"fellowship"},
{n:"Gandhi Fellowship (Piramal)",d:"2-year school transformation. Education policy at district level.",t:"fellowship"},
{n:"Teach For India",d:"2-year classroom + systemic reform. Major education policy pipeline.",t:"fellowship"},
{n:"Policy Sangam Fellowship (PPI)",d:"Launching Aug 15, 2026. 75 fellows. 6-week hybrid. Three tracks.",t:"fellowship"},
{n:"Clinton Fellowship (AIF)",d:"10-month. Young Americans and Indians in development organisations.",t:"fellowship"},
{n:"India Leaders for Social Sector",d:"1-year. Mid-career professionals in social sector leadership.",t:"fellowship"},
{n:"JSGP (Jindal)",d:"Est. 2011. >80% placement, avg ~\u20b97.5 LPA, median ~\u20b96.6 LPA.",t:"education"},
{n:"Kautilya School",d:"Est. 2020. ~90% placement, avg ~\u20b915 LPA, highest ~\u20b946.5 LPA.",t:"education"},
{n:"Azim Premji University",d:"~\u20b92.73L total (subsidised). ~90% enter social sector.",t:"education"},
{n:"Takshashila (Online)",d:"7,000+ alumni. 12-week certificate for ~\u20b942K. Accessible anywhere.",t:"education"},
{n:"ISPP",d:"150+ partner orgs. Market-oriented. Kelkar & Shah framework.",t:"education"},
{n:"TISS",d:"Social work tradition. Mumbai, Hyderabad, Guwahati.",t:"education"},
{n:"IITs (Delhi/Bombay/Madras MPP)",d:"Post-NEP 2020. Engineering + policy. Still maturing.",t:"education"},
{n:"IIM Bangalore PGPPM",d:"Earliest (2002). 2025 redesign. ~\u20b920L fees.",t:"education"},
{n:"NLSIU MPP",d:"Law integrated throughout. Legal-policy intersection.",t:"education"},
{n:"Ashoka YIF",d:"1-year postgrad diploma. Significant policy feeder.",t:"education"},
{n:"MPH Programmes (PHFI, IIHMR, TISS)",d:"For public health policy. Epidemiology + policy. Growing post-COVID.",t:"education"},
{n:"NITI Aayog Young Professionals",d:"~\u20b970K/mo, 2 years. Extraordinary access. Highly competitive.",t:"government"},
{n:"UPSC Civil Services",d:"10L+ apply, ~1,000 seats. 2\u20134 year prep. The gravitational pull.",t:"government"},
{n:"State PSC Examinations",d:"State-specific. Lower competition. Deep local impact.",t:"government"},
{n:"Lateral Entry (currently stalled)",d:"45 positions advertised Aug 2024, cancelled 72hrs later. Concept relevant.",t:"government"},
{n:"Dev Consulting entry (Dalberg/Sattva/FSG)",d:"Subsidised training: skills, buffer, then move. Case interview typical.",t:"consulting"},
{n:"Think Tank Internship Pipeline",d:"CEEW, CPR, ORF, Vidhi. 2\u20136 months. Reliable path to FT roles.",t:"research"},
{n:"Corporate GAPA Entry",d:"Google, Meta, Amazon. Needs 2\u20135 yrs prior. Highest ceiling.",t:"corporate"},
{n:"UN Volunteers / JPO",d:"Stepping stones to multilateral careers. Consultancies = foot-in-door.",t:"multilateral"},
{n:"Ashoka CSIP",d:"Liberal arts to development sector bridge. Growing alumni in policy.",t:"education"},
{n:"Anubhav Lecture Series",d:"Knowledge transfer from retiring civil servants. Governance insights.",t:"government"},
{n:"ICFRE / Environment Fellowships",d:"Environment and forestry research fellowships under MoEFCC.",t:"fellowship"},
{n:"Azim Premji Foundation Fellowship",d:"2-year grassroots immersion in education, governance, or health.",t:"fellowship"},
];

const QZ=[
{q:"What pulls you toward this work?",opts:[{l:"A system failed someone I know",tg:["NGO / Civil Society","Government"]},{l:"Understanding how decisions are made at scale",tg:["Think Tank","Legal & Regulatory","Academia"]},{l:"Building something millions use",tg:["Government","Social Enterprise","Dev Consulting"]},{l:"Being where power meets information",tg:["Corporate GAPA","Political Strategy"]},{l:"Shaping narratives and public understanding",tg:["Policy Communication","Academia"]},{l:"Enabling and funding others doing the work",tg:["Philanthropy / CSR","Multilateral / IO"]}]},
{q:"Your academic background?",opts:[{l:"Social Sciences / Humanities",tg:["Think Tank","NGO / Civil Society","Policy Communication"]},{l:"Law",tg:["Legal & Regulatory","Corporate GAPA"]},{l:"Economics / Finance",tg:["Dev Consulting","Philanthropy / CSR","Multilateral / IO"]},{l:"Engineering / STEM / Data",tg:["Social Enterprise","Think Tank"]},{l:"Medicine / Public Health",tg:["Multilateral / IO","NGO / Civil Society"]},{l:"Journalism / Media",tg:["Policy Communication"]},{l:"Management / MBA",tg:["Dev Consulting","Corporate GAPA","Philanthropy / CSR"]}]},
{q:"What does a satisfying workday look like?",opts:[{l:"Deep writing and argument-building over weeks",tg:["Think Tank","Academia","Legal & Regulatory"]},{l:"Meetings, stakeholders, institutional politics",tg:["Government","Corporate GAPA","Multilateral / IO"]},{l:"Fieldwork, communities, ground reality",tg:["NGO / Civil Society"]},{l:"Data, dashboards, building evidence",tg:["Think Tank","Dev Consulting","Social Enterprise"]},{l:"Client deliverables and fast context-switching",tg:["Dev Consulting","Corporate GAPA"]},{l:"Creating content that reaches large audiences",tg:["Policy Communication"]}]},
{q:"Your compensation priority?",opts:[{l:"Financial stability right now",tg:["Corporate GAPA","Dev Consulting","Legal & Regulatory"]},{l:"Lower pay for meaningful work (at least for now)",tg:["NGO / Civil Society","Think Tank","Government","Policy Communication"]},{l:"Compensation that catches up over time",tg:["Government","Dev Consulting","Multilateral / IO"]},{l:"The highest ceiling this field can offer",tg:["Corporate GAPA","Social Enterprise","Legal & Regulatory"]}]},
{q:"How do you handle ambiguity?",opts:[{l:"Show me a clear career ladder",tg:["Government","Corporate GAPA","Legal & Regulatory"]},{l:"Fine if the work is intellectually stimulating",tg:["Think Tank","Dev Consulting","Multilateral / IO","Academia"]},{l:"I actively create roles that don't exist yet",tg:["Social Enterprise","Policy Communication","Political Strategy"]},{l:"I want to try many things before committing",tg:["Dev Consulting","Multilateral / IO"]}]},
{q:"Where do you want to be based?",opts:[{l:"Delhi (central govt, think tanks, multilaterals)",tg:["Think Tank","Government","Multilateral / IO","Corporate GAPA"]},{l:"Mumbai / Bangalore (consulting, startups, corporate)",tg:["Dev Consulting","Social Enterprise","Corporate GAPA","Philanthropy / CSR"]},{l:"State capitals (state government, regional policy)",tg:["Government","NGO / Civil Society","Political Strategy"]},{l:"Smaller cities / rural India (implementation)",tg:["NGO / Civil Society"]},{l:"Open to travel and relocation",tg:["Dev Consulting","Multilateral / IO"]}]},
];

const PR=[
{n:1,t:"Invest in Human Skills",q:"One day the only jobs people will do will be jobs only people can do. That day is arriving faster than expected.",d:"Reading a room, building trust with a sceptical bureaucrat, explaining a complex finding to a minister in four minutes: these are the hard core of policy effectiveness. AI can draft your brief. It cannot negotiate your coalition."},
{n:2,t:"Find Your Competitive Advantage",q:"Sample ten flavours before you buy one. You will always lose to a person who is having fun at what they do.",d:"The profession is broad enough that almost everyone can find a niche where their specific combination of skills, interests, and personality is a genuine advantage."},
{n:3,t:"Show, Don't Tell",q:"Well-expressed evidence of your skills counts for more than claims about them.",d:"Don't write strong writing skills on your CV; link to the policy brief. Don't claim data analysis; share the dashboard you built. In this field, the portfolio is the resume."},
{n:4,t:"Increase Your Luck Surface Area",q:"Spread the word. Make it easier for people to discover and engage with your work.",d:"Fill gaps rather than compete. PPI grew because it was creating something that did not previously exist, not outcompeting established players."},
{n:5,t:"Shun Competition, Identify Gaps",q:"If you wait for permission, you will keep waiting.",d:"The most interesting opportunities did not exist until someone created them. A fellowship that did not exist in 2008 now spans 8+ states."},
{n:6,t:"Shape Your Values",q:"A large chunk of hiring is, frankly, a vibe check.",d:"Are you someone others want to work with under pressure, in ambiguous situations, when the stakes are real?"},
];

const FIVER=[
{step:"Reflect",d:"Have that conversation with yourself: why this field, this org, this role? What motivates you? It matters for the story you tell."},
{step:"Research",d:"Go deep. Which organisations work here? What roles do they hire for? What skills do they need? Reach out on LinkedIn."},
{step:"Ready",d:"Work on your resume, LinkedIn, portfolio. Don't just list skills; link to the brief you wrote, the dashboard you built."},
{step:"Reach Out",d:"Apply with your best portfolio. Also reach out to individuals; ask for conversations, seek referrals. More useful than you think."},
{step:"Repeat",d:"If after a couple of months you are still looking, repeat the cycle. Identify errors, adjust. Get your foot in the door."},
];

/* ====== REACT COMPONENT ====== */
export default function App(){
const[tab,setTab]=useState("roles");const[sel,setSel]=useState(null);const[spF,setSpF]=useState("All");const[lvF,setLvF]=useState("All");const[q,setQ]=useState("");
const[qs,setQs]=useState(0);const[qa,setQa]=useState({});const[qd,setQd]=useState(false);
const[pF,setPF]=useState("all");const[skC,setSkC]=useState(null);const[skS,setSkS]=useState(null);
const[cmp,setCmp]=useState([]);
const filt=useMemo(()=>{let f=R;if(spF!=="All")f=f.filter(r=>r.space===spF);if(lvF!=="All")f=f.filter(r=>LEVELS[r.level]===lvF);if(q){const s=q.toLowerCase();f=f.filter(r=>r.title.toLowerCase().includes(s)||r.desc.toLowerCase().includes(s)||r.space.toLowerCase().includes(s)||r.skills.some(sk=>sk.toLowerCase().includes(s)));}return f;},[spF,lvF,q]);
const qRes=useMemo(()=>{if(!qd)return null;const sc={};SN.forEach(s=>sc[s]=0);Object.values(qa).forEach(o=>{if(o&&o.tg)o.tg.forEach(t=>{if(sc[t]!==undefined)sc[t]++;});});return Object.entries(sc).sort((a,b)=>b[1]-a[1]).filter(([_,v])=>v>0).slice(0,5).map(([s,v])=>({space:s,score:v,roles:R.filter(r=>r.space===s)}));},[qd,qa]);
const skRoles=useMemo(()=>{if(!skS)return[];const s=skS.toLowerCase();return R.filter(r=>r.skills.some(sk=>sk.toLowerCase().includes(s.split("(")[0].trim().split("/")[0].trim())));},[skS]);
const togCmp=useCallback((id)=>setCmp(p=>p.includes(id)?p.filter(x=>x!==id):p.length<3?[...p,id]:p),[]);
const cmpR=cmp.map(id=>R.find(r=>r.id===id)).filter(Boolean);
const go=useCallback((r)=>{setTab("roles");setSel(r);window.scrollTo({top:0,behavior:"smooth"});},[]);
const pill=(a,c=C.pri)=>({padding:"7px 15px",borderRadius:20,fontSize:12,fontWeight:a?600:500,background:a?c:C.card,color:a?"#fff":C.mid,border:a?"none":`1px solid ${C.border}`,cursor:"pointer",boxShadow:a?"none":C.sh,transition:"all .2s",whiteSpace:"nowrap"});
const cd=()=>({background:C.card,border:`1px solid ${C.border}`,borderRadius:16,padding:"20px",boxShadow:C.sh,position:"relative",overflow:"hidden"});
const lb=()=>({fontSize:10,color:C.lt,textTransform:"uppercase",letterSpacing:"0.08em",fontWeight:700});
const TABS=[{id:"roles",l:"Role Explorer",i:"\u25c6"},{id:"quiz",l:"Career Quiz",i:"\u25c7"},{id:"ladder",l:"Career Ladders",i:"\u2195"},{id:"skills",l:"Skills Map",i:"\u2727"},{id:"paths",l:"Pathways",i:"\u2192"},{id:"compass",l:"Compass",i:"\u2726"}];

const PPICta=()=>(<div style={{...cd(),background:`linear-gradient(135deg,${C.priBg},${C.cream})`,borderTop:`3px solid ${C.pri}`,marginTop:28}}><div style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:600,color:C.text,marginBottom:12}}>Continue Your Journey</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><div style={{background:C.card,borderRadius:12,padding:16,border:`1px solid ${C.borderLt}`}}><div style={{fontSize:13,fontWeight:600,color:C.text,marginBottom:6}}>{"📬 The Policy Post Newsletter"}</div><p style={{fontSize:12,color:C.mid,lineHeight:1.6,marginBottom:10}}>Every Friday: a fresh database of 100s of jobs, internships, courses, essays, videos, and podcasts in the policy and social impact space. Completely free. Read by 22,000+ professionals.</p><a href="https://newsletter.publicpolicyindia.com" target="_blank" rel="noopener noreferrer" style={{display:"inline-block",padding:"8px 18px",borderRadius:10,background:C.pri,color:"#fff",fontSize:12,fontWeight:600,textDecoration:"none"}}>Subscribe Free →</a></div><div style={{background:C.card,borderRadius:12,padding:16,border:`1px solid ${C.borderLt}`}}><div style={{fontSize:13,fontWeight:600,color:C.text,marginBottom:6}}>{"🏙️ City Chapters Across India"}</div><p style={{fontSize:12,color:C.mid,lineHeight:1.6,marginBottom:10}}>Policy and social impact communities in 20+ cities. In-person meetups, career exchanges, learning sessions, and networking with professionals in your city.</p><a href="https://drive.google.com/file/d/1rk2FMz_3w-EVuQMMZanc5gkrcG3AU9CA/view?usp=sharing" target="_blank" rel="noopener noreferrer" style={{display:"inline-block",padding:"8px 18px",borderRadius:10,background:C.navy,color:"#fff",fontSize:12,fontWeight:600,textDecoration:"none"}}>Join Your City →</a></div></div></div>);

return(<div style={{fontFamily:"'Manrope',sans-serif",background:C.bg,color:C.text,minHeight:"100vh"}}><style>{`@import url('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,300;9..144,400;9..144,500;9..144,600;9..144,700&family=Manrope:wght@300;400;500;600;700&display=swap');*{box-sizing:border-box;margin:0;padding:0}::selection{background:${C.pri}20;color:${C.pri}}@keyframes fu{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}.fu{animation:fu .4s ease-out forwards}button,input,a{font-family:'Manrope',sans-serif}::-webkit-scrollbar{width:5px}::-webkit-scrollbar-thumb{background:rgba(28,28,48,.08);border-radius:3px}a{color:inherit}`}</style>

{/* HEADER */}
<header style={{borderBottom:`1px solid ${C.border}`,padding:"12px 20px",display:"flex",alignItems:"center",justifyContent:"space-between",background:"#FEFDFB",position:"sticky",top:0,zIndex:100}}>
<div style={{display:"flex",alignItems:"center",gap:10}}><PPILogo size={34}/><div><div style={{fontFamily:"'Fraunces',serif",fontSize:16,fontWeight:600,letterSpacing:"-0.02em"}}>Policy Career Navigator</div><div style={{fontSize:9.5,color:C.lt,letterSpacing:"0.06em",textTransform:"uppercase"}}>by Public Policy India</div></div></div>
<div style={{fontSize:11,color:C.lt,display:"flex",gap:10,alignItems:"center"}}><span style={{fontWeight:600,color:C.pri}}>{R.length}</span><span>roles</span><span style={{color:C.borderLt}}>|</span><span style={{fontWeight:600,color:C.coral}}>{SK.reduce((a,c)=>a+c.skills.length,0)}</span><span>skills</span><span style={{color:C.borderLt}}>|</span><span style={{fontWeight:600,color:C.navy}}>{PA.length}</span><span>pathways</span></div></header>

{/* NAV */}
<nav style={{display:"flex",borderBottom:`1px solid ${C.border}`,background:"#FEFCF8",overflowX:"auto",position:"sticky",top:58,zIndex:99}}>
{TABS.map(t=><button key={t.id} onClick={()=>{setTab(t.id);setSel(null);setSkS(null);}} style={{flex:"1 0 auto",padding:"13px 14px",background:tab===t.id?C.priBg:"transparent",border:"none",borderBottom:tab===t.id?`2.5px solid ${C.pri}`:"2.5px solid transparent",color:tab===t.id?C.pri:C.lt,cursor:"pointer",fontSize:12,fontWeight:tab===t.id?700:500,transition:"all .2s",whiteSpace:"nowrap"}}>{t.i} {t.l}</button>)}</nav>

<main style={{maxWidth:980,margin:"0 auto",padding:"24px 18px 40px"}}>

{/* ROLE EXPLORER */}
{tab==="roles"&&!sel&&<div className="fu">
<h1 style={{fontFamily:"'Fraunces',serif",fontSize:28,fontWeight:600,marginBottom:4}}>Role Explorer</h1>
<p style={{fontSize:14,color:C.mid,marginBottom:18,lineHeight:1.6}}>Browse {R.length} specific roles across {SN.length} career spaces in India's policy, social impact, law, and governance ecosystem. All salary figures are approximate ranges based on placement reports, Glassdoor India, and industry estimates.</p>
<div style={{display:"flex",gap:8,marginBottom:10,flexWrap:"wrap",alignItems:"center"}}>
<input placeholder="Search roles, skills, keywords..." value={q} onChange={e=>setQ(e.target.value)} style={{padding:"8px 16px",borderRadius:10,background:C.card,border:`1px solid ${C.border}`,color:C.text,fontSize:13,width:260,outline:"none",boxShadow:C.sh}}/>
<span style={{...lb(),padding:"0 4px"}}>Stage:</span>
{["All",...LEVELS].map(l=><button key={l} onClick={()=>setLvF(l)} style={pill(lvF===l,LC[LEVELS.indexOf(l)]||C.pri)}>{l}</button>)}</div>
<div style={{display:"flex",gap:5,marginBottom:18,flexWrap:"wrap"}}>
<span style={{...lb(),padding:"6px 4px 6px 0"}}>Space:</span>
{["All",...SN].map(s=><button key={s} onClick={()=>setSpF(s)} style={pill(spF===s,SC[s]||C.pri)}>{s}</button>)}</div>
{cmp.length>0&&<div style={{...cd(),marginBottom:14,borderLeft:`4px solid ${C.coral}`,display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:8}}><div style={{fontSize:12,fontWeight:600,color:C.coral}}>Comparing {cmp.length}/3</div><div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}>{cmpR.map(r=><span key={r.id} onClick={()=>togCmp(r.id)} style={{fontSize:11,padding:"4px 10px",borderRadius:14,background:`${C.coral}10`,color:C.coral,cursor:"pointer"}}>{r.title} ✕</span>)}<button onClick={()=>setSel({compare:true})} style={{padding:"6px 16px",borderRadius:8,background:C.coral,border:"none",color:"#fff",cursor:"pointer",fontSize:12,fontWeight:600}}>Compare →</button></div></div>}
<div style={{fontSize:12,color:C.lt,marginBottom:8}}>{filt.length} role{filt.length!==1?"s":""} found</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:12}}>
{filt.map(r=>{const sc=SC[r.space]||C.pri;const lc=LC[r.level];return(<div key={r.id} style={{...cd(),cursor:"pointer",transition:"box-shadow .2s,transform .2s",borderTop:`3px solid ${sc}`}} onClick={()=>setSel(r)} onMouseOver={e=>{e.currentTarget.style.boxShadow=C.shH;e.currentTarget.style.transform="translateY(-1px)";}} onMouseOut={e=>{e.currentTarget.style.boxShadow=C.sh;e.currentTarget.style.transform="translateY(0)";}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:8}}><div><div style={{fontFamily:"'Fraunces',serif",fontSize:15,fontWeight:600,lineHeight:1.25}}>{r.title}</div><div style={{fontSize:11,color:sc,fontWeight:500,marginTop:2}}>{r.space}</div></div>
<button onClick={e=>{e.stopPropagation();togCmp(r.id);}} title="Compare" style={{width:26,height:26,borderRadius:7,background:cmp.includes(r.id)?`${C.coral}12`:C.warm,border:cmp.includes(r.id)?`1.5px solid ${C.coral}`:`1px solid ${C.borderLt}`,cursor:"pointer",fontSize:11,color:cmp.includes(r.id)?C.coral:C.faint,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>⇔</button></div>
<p style={{fontSize:12,color:C.mid,lineHeight:1.55,marginBottom:10}}>{r.desc.substring(0,130)}{r.desc.length>130?"...":""}</p>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><span style={{fontSize:10.5,padding:"3px 10px",borderRadius:14,background:`${lc}10`,color:lc,fontWeight:600}}>{LEVELS[r.level]}</span><span style={{fontSize:12.5,color:C.text,fontWeight:600}}>{r.salary}</span></div>
<div style={{display:"flex",flexWrap:"wrap",gap:3}}>{r.skills.slice(0,4).map((s,i)=><span key={i} style={{fontSize:10,padding:"2px 8px",borderRadius:10,background:C.warm,color:C.mid}}>{s}</span>)}{r.skills.length>4&&<span style={{fontSize:10,color:C.faint}}>+{r.skills.length-4}</span>}</div>
</div>);})}</div><PPICta/></div>}

{/* ROLE DETAIL */}
{tab==="roles"&&sel&&!sel.compare&&<div className="fu">
<button onClick={()=>setSel(null)} style={{background:"none",border:"none",color:C.pri,cursor:"pointer",fontSize:13,fontWeight:600,marginBottom:14}}>← All roles</button>
<div style={{...cd(),borderTop:`4px solid ${SC[sel.space]||C.pri}`}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:16,flexWrap:"wrap",gap:8}}><div><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:6}}><span style={{fontSize:10.5,padding:"3px 10px",borderRadius:14,background:`${LC[sel.level]}10`,color:LC[sel.level],fontWeight:600}}>{LEVELS[sel.level]}</span><span style={{fontSize:11,color:SC[sel.space],fontWeight:500}}>{sel.space}</span></div><h1 style={{fontFamily:"'Fraunces',serif",fontSize:26,fontWeight:600,lineHeight:1.2}}>{sel.title}</h1></div><div style={{fontFamily:"'Fraunces',serif",fontSize:20,fontWeight:700,color:C.pri}}>{sel.salary}</div></div>
<p style={{fontSize:14,color:C.mid,lineHeight:1.8,marginBottom:22}}>{sel.desc}</p>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14,marginBottom:20}}><div style={{background:C.warm,borderRadius:12,padding:16}}><div style={lb()}>Requirements</div><p style={{fontSize:13,color:C.mid,lineHeight:1.65,marginTop:6}}>{sel.req}</p></div><div style={{background:C.warm,borderRadius:12,padding:16}}><div style={lb()}>Sample Organisations</div><div style={{display:"flex",flexWrap:"wrap",gap:5,marginTop:6}}>{sel.orgs.map((o,i)=><span key={i} style={{fontSize:12,padding:"4px 11px",borderRadius:8,background:C.card,border:`1px solid ${C.borderLt}`,color:C.mid}}>{o}</span>)}</div></div></div>
<div style={{marginBottom:20}}><div style={lb()}>Skills Required</div><div style={{display:"flex",flexWrap:"wrap",gap:6,marginTop:8}}>{sel.skills.map((s,i)=><span key={i} style={{fontSize:12,padding:"7px 15px",borderRadius:10,background:`${SC[sel.space]||C.pri}06`,border:`1px solid ${SC[sel.space]||C.pri}18`,color:C.text,fontWeight:450}}>{s}</span>)}</div></div>
{sel.verticals&&sel.verticals[0]!=="Any sector"&&<div style={{marginBottom:20}}><div style={lb()}>Typical Sectors</div><div style={{display:"flex",gap:6,marginTop:6,flexWrap:"wrap"}}>{sel.verticals.map((v,i)=><span key={i} style={{fontSize:11,padding:"4px 12px",borderRadius:14,background:`${C.amber}0C`,color:C.amber,fontWeight:500}}>{v}</span>)}</div></div>}
{sel.next&&sel.next.length>0&&<div><div style={lb()}>Where This Role Leads</div><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:8}}>{sel.next.map(nid=>{const nr=R.find(r=>r.id===nid);if(!nr)return null;return(<button key={nid} onClick={()=>{setSel(nr);window.scrollTo({top:0,behavior:"smooth"});}} style={{...cd(),cursor:"pointer",padding:"12px 16px",display:"flex",alignItems:"center",gap:10,flex:"1 0 200px",transition:"box-shadow .2s",borderLeft:`3px solid ${LC[nr.level]}`}} onMouseOver={e=>e.currentTarget.style.boxShadow=C.shH} onMouseOut={e=>e.currentTarget.style.boxShadow=C.sh}><div><div style={{fontSize:13,fontWeight:600}}>{nr.title}</div><div style={{fontSize:11,color:C.lt}}>{LEVELS[nr.level]} · {nr.salary}</div></div><span style={{marginLeft:"auto",fontSize:12,color:C.pri}}>→</span></button>);})}</div></div>}
</div><PPICta/></div>}

{/* COMPARE */}
{tab==="roles"&&sel&&sel.compare&&<div className="fu">
<button onClick={()=>setSel(null)} style={{background:"none",border:"none",color:C.pri,cursor:"pointer",fontSize:13,fontWeight:600,marginBottom:14}}>← Back</button>
<h1 style={{fontFamily:"'Fraunces',serif",fontSize:24,fontWeight:600,marginBottom:16}}>Side-by-Side Comparison</h1>
<div style={{display:"grid",gridTemplateColumns:`repeat(${cmpR.length},1fr)`,gap:14}}>{cmpR.map(r=>(<div key={r.id} style={{...cd(),borderTop:`3px solid ${LC[r.level]}`}}><h3 style={{fontFamily:"'Fraunces',serif",fontSize:16,fontWeight:600,marginBottom:2}}>{r.title}</h3><div style={{fontSize:11,color:SC[r.space],fontWeight:500,marginBottom:12}}>{r.space}</div>
{[["Stage",LEVELS[r.level]],["Salary",r.salary]].map(([k,v])=><div key={k} style={{marginBottom:10}}><div style={lb()}>{k}</div><div style={{fontSize:13,color:C.text,fontWeight:600,marginTop:2}}>{v}</div></div>)}
<div style={{marginBottom:10}}><div style={lb()}>Requirements</div><div style={{fontSize:12,color:C.mid,lineHeight:1.5,marginTop:2}}>{r.req}</div></div>
<div><div style={lb()}>Skills</div><div style={{display:"flex",flexWrap:"wrap",gap:3,marginTop:4}}>{r.skills.map((s,i)=><span key={i} style={{fontSize:10,padding:"2px 7px",borderRadius:8,background:C.warm,color:C.mid}}>{s}</span>)}</div></div></div>))}</div></div>}

{/* QUIZ */}
{tab==="quiz"&&!qd&&<div className="fu" style={{maxWidth:640,margin:"0 auto"}}>
<h1 style={{fontFamily:"'Fraunces',serif",fontSize:28,fontWeight:600,textAlign:"center",marginBottom:4}}>Career Discovery Quiz</h1>
<p style={{fontSize:14,color:C.mid,textAlign:"center",marginBottom:24,lineHeight:1.6}}>Six questions mapping your instincts to {SN.length} spaces and {R.length} specific roles.</p>
<div style={{display:"flex",gap:4,justifyContent:"center",marginBottom:24}}>{QZ.map((_,i)=><div key={i} style={{width:i===qs?32:12,height:4,borderRadius:2,background:i<qs?C.pri:i===qs?`${C.pri}90`:`${C.pri}15`,transition:"all .3s"}}/>)}</div>
<div key={qs} className="fu" style={cd()}>
<div style={{fontSize:11,color:C.pri,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:10}}>Question {qs+1} of {QZ.length}</div>
<h2 style={{fontFamily:"'Fraunces',serif",fontSize:22,fontWeight:500,marginBottom:18,lineHeight:1.3}}>{QZ[qs].q}</h2>
<div style={{display:"flex",flexDirection:"column",gap:8}}>{QZ[qs].opts.map((o,i)=><button key={i} onClick={()=>{const na={...qa,[qs]:o};setQa(na);if(qs<QZ.length-1)setTimeout(()=>setQs(qs+1),220);else setTimeout(()=>setQd(true),250);}} style={{background:qa[qs]?.l===o.l?`${C.pri}08`:C.warm,border:qa[qs]?.l===o.l?`1.5px solid ${C.pri}40`:`1.5px solid ${C.borderLt}`,borderRadius:11,padding:"13px 18px",color:C.text,cursor:"pointer",fontSize:13.5,textAlign:"left",transition:"all .2s",lineHeight:1.5}}>{o.l}</button>)}</div>
{qs>0&&<button onClick={()=>setQs(qs-1)} style={{marginTop:16,background:"none",border:"none",color:C.lt,cursor:"pointer",fontSize:12.5,fontWeight:500}}>← Previous</button>}</div></div>}

{tab==="quiz"&&qd&&qRes&&<div className="fu">
<h1 style={{fontFamily:"'Fraunces',serif",fontSize:28,fontWeight:600,textAlign:"center",marginBottom:4}}>Your Policy Career Map</h1>
<p style={{fontSize:14,color:C.mid,textAlign:"center",marginBottom:24,lineHeight:1.6}}>Your top spaces and specific roles within each. Tap any role for the full profile.</p>
{qRes.map((s,i)=><div key={i} style={{...cd(),marginBottom:14,borderLeft:`4px solid ${SC[s.space]||LC[i%5]}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><h2 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:600,color:SC[s.space]}}>#{i+1} {s.space}</h2><span style={{fontSize:12,color:C.lt}}>{s.roles.length} roles</span></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(220px,1fr))",gap:8}}>{s.roles.map(r=><button key={r.id} onClick={()=>go(r)} style={{...cd(),cursor:"pointer",textAlign:"left",padding:"12px 14px",borderTop:`2px solid ${LC[r.level]}`,transition:"box-shadow .2s"}} onMouseOver={e=>e.currentTarget.style.boxShadow=C.shH} onMouseOut={e=>e.currentTarget.style.boxShadow=C.sh}><div style={{fontSize:13,fontWeight:600,marginBottom:2}}>{r.title}</div><div style={{fontSize:11,color:C.lt}}>{LEVELS[r.level]} · {r.salary}</div></button>)}</div></div>)}
<div style={{...cd(),marginTop:20,borderLeft:`4px solid ${C.pri}`}}><h3 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:600,marginBottom:14}}>The 5R Framework: How to Land a Job</h3>{FIVER.map((f,i)=><div key={i} style={{display:"flex",gap:14,marginBottom:12,alignItems:"flex-start"}}><div style={{width:32,height:32,borderRadius:10,background:`${C.pri}10`,color:C.pri,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:700,flexShrink:0}}>{i+1}</div><div><div style={{fontSize:14,fontWeight:600,color:C.text,marginBottom:2}}>{f.step}</div><div style={{fontSize:12.5,color:C.mid,lineHeight:1.6}}>{f.d}</div></div></div>)}</div>
<button onClick={()=>{setQs(0);setQa({});setQd(false);}} style={{padding:"10px 22px",borderRadius:10,background:C.pri,border:"none",color:"#fff",cursor:"pointer",fontSize:13,fontWeight:600,marginTop:16}}>Retake Quiz</button><PPICta/></div>}

{/* CAREER LADDERS */}
{tab==="ladder"&&<div className="fu">
<h1 style={{fontFamily:"'Fraunces',serif",fontSize:28,fontWeight:600,marginBottom:4}}>Career Ladders</h1>
<p style={{fontSize:14,color:C.mid,marginBottom:24,lineHeight:1.6}}>How roles progress from Entry to Leadership. Tap any role for details.</p>
{SN.filter(s=>R.some(r=>r.space===s)).map(space=>{const roles=R.filter(r=>r.space===space).sort((a,b)=>a.level-b.level);const sc=SC[space]||C.pri;return(<div key={space} style={{...cd(),marginBottom:16,borderLeft:`4px solid ${sc}`}}><h3 style={{fontFamily:"'Fraunces',serif",fontSize:17,fontWeight:600,color:sc,marginBottom:14}}>{space} <span style={{fontSize:12,color:C.lt,fontWeight:400}}>({roles.length} roles)</span></h3>
<div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:6}}>{LEVELS.map((lev,li)=>{const lr=roles.filter(r=>r.level===li);if(!lr.length)return <div key={li} style={{minWidth:130,textAlign:"center",padding:10,fontSize:11,color:C.faint,opacity:.5}}>{lev}</div>;return(<div key={li} style={{minWidth:155,flex:"1 0 155px"}}><div style={{fontSize:10,color:LC[li],fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:8,textAlign:"center"}}>{lev}</div>{lr.map(r=><button key={r.id} onClick={()=>go(r)} style={{width:"100%",marginBottom:6,background:C.card,border:`1px solid ${C.border}`,borderRadius:10,borderLeft:`3px solid ${LC[li]}`,cursor:"pointer",padding:"10px 12px",textAlign:"left",boxShadow:C.sh,transition:"box-shadow .2s"}} onMouseOver={e=>e.currentTarget.style.boxShadow=C.shH} onMouseOut={e=>e.currentTarget.style.boxShadow=C.sh}><div style={{fontSize:12,fontWeight:600,color:C.text}}>{r.title}</div><div style={{fontSize:10,color:C.lt,marginTop:2}}>{r.salary}</div></button>)}</div>);})}</div></div>);})}
<PPICta/></div>}

{/* SKILLS MAP */}
{tab==="skills"&&<div className="fu">
<h1 style={{fontFamily:"'Fraunces',serif",fontSize:28,fontWeight:600,marginBottom:4}}>Skills Map</h1>
<p style={{fontSize:14,color:C.mid,marginBottom:20,lineHeight:1.6}}>{SK.reduce((a,c)=>a+c.skills.length,0)} skills across {SK.length} categories. Tap any skill to see which roles require it.</p>
<div style={{display:"flex",gap:7,marginBottom:20,flexWrap:"wrap"}}><button onClick={()=>{setSkC(null);setSkS(null);}} style={pill(!skC,C.pri)}>All Categories</button>{SK.map(c=><button key={c.cat} onClick={()=>{setSkC(c.cat);setSkS(null);}} style={pill(skC===c.cat,c.c)}>{c.cat}</button>)}</div>
{SK.filter(c=>!skC||c.cat===skC).map(c=><div key={c.cat} style={{marginBottom:26}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><div style={{width:14,height:14,borderRadius:4,background:c.c}}/><div style={{fontFamily:"'Fraunces',serif",fontSize:17,fontWeight:600}}>{c.cat}</div><span style={{fontSize:11,color:C.lt}}>{c.skills.length} skills</span></div>
<div style={{display:"flex",flexWrap:"wrap",gap:7}}>{c.skills.map((sk,i)=>{const isA=skS===sk;const mc=R.filter(r=>r.skills.some(rs=>{const w=sk.toLowerCase().split(/[\s\/\(\),&]+/).filter(x=>x.length>2);return w.some(x=>rs.toLowerCase().includes(x));})).length;return(<button key={i} onClick={()=>setSkS(isA?null:sk)} style={{fontSize:12,padding:"8px 15px",borderRadius:10,background:isA?c.c:C.card,color:isA?"#fff":C.mid,border:isA?"none":`1px solid ${C.border}`,boxShadow:isA?"none":C.sh,cursor:"pointer",display:"flex",alignItems:"center",gap:6,fontWeight:isA?600:450,transition:"all .2s"}}>{sk}{mc>0&&<span style={{fontSize:9,padding:"1px 6px",borderRadius:8,background:isA?"rgba(255,255,255,.25)":`${c.c}12`,color:isA?"#fff":c.c,fontWeight:600}}>{mc}</span>}</button>);})}</div></div>)}
{skS&&<div style={{...cd(),marginTop:8,borderTop:`3px solid ${C.pri}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div><div style={lb()}>Roles requiring</div><div style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:600,marginTop:2}}>"{skS}"</div></div><button onClick={()=>setSkS(null)} style={{background:C.warm,border:`1px solid ${C.borderLt}`,borderRadius:8,padding:"6px 14px",cursor:"pointer",fontSize:12,color:C.mid}}>Clear ✕</button></div>
{skRoles.length===0?<p style={{fontSize:13,color:C.lt}}>No exact matches. Try a different skill.</p>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(250px,1fr))",gap:10}}>{skRoles.map(r=><button key={r.id} onClick={()=>go(r)} style={{...cd(),cursor:"pointer",textAlign:"left",padding:"12px 14px",borderLeft:`3px solid ${LC[r.level]}`,transition:"box-shadow .2s"}} onMouseOver={e=>e.currentTarget.style.boxShadow=C.shH} onMouseOut={e=>e.currentTarget.style.boxShadow=C.sh}><div style={{fontSize:13,fontWeight:600}}>{r.title}</div><div style={{fontSize:11,color:C.lt}}>{r.space} · {LEVELS[r.level]} · {r.salary}</div></button>)}</div>}</div>}
<PPICta/></div>}

{/* PATHWAYS */}
{tab==="paths"&&<div className="fu">
<h1 style={{fontFamily:"'Fraunces',serif",fontSize:28,fontWeight:600,marginBottom:4}}>Entry Pathways</h1>
<p style={{fontSize:14,color:C.mid,marginBottom:20,lineHeight:1.6}}>{PA.length} pathways into the policy ecosystem. India has no formal pipeline: people find the field through these channels.</p>
<div style={{display:"flex",gap:7,marginBottom:18,flexWrap:"wrap"}}>{["all","fellowship","education","government","consulting","research","corporate","multilateral"].map(f=><button key={f} onClick={()=>setPF(f)} style={pill(pF===f,C.pri)}>{f==="all"?"All":f.charAt(0).toUpperCase()+f.slice(1)}</button>)}</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:10}}>{PA.filter(p=>pF==="all"||p.t===pF).map((p,i)=>{const cols={fellowship:C.pri,education:C.navy,government:C.emerald,consulting:C.coral,research:C.slate,corporate:C.plum,multilateral:C.amber};const pc=cols[p.t]||C.pri;return(<div key={i} style={{...cd(),borderLeft:`3px solid ${pc}`}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}><span style={{fontSize:10,padding:"2px 8px",borderRadius:10,background:`${pc}10`,color:pc,fontWeight:600,textTransform:"uppercase"}}>{p.t}</span><div style={{fontFamily:"'Fraunces',serif",fontSize:14,fontWeight:600}}>{p.n}</div></div><p style={{fontSize:12.5,color:C.mid,lineHeight:1.6}}>{p.d}</p></div>);})}</div><PPICta/></div>}

{/* COMPASS */}
{tab==="compass"&&<div className="fu">
<h1 style={{fontFamily:"'Fraunces',serif",fontSize:28,fontWeight:600,marginBottom:4}}>Career Compass</h1>
<p style={{fontSize:14,color:C.mid,marginBottom:24,lineHeight:1.6}}>Six principles for navigating policy careers. From seven years across Parliament, Twitter, ICANN, consulting, universities, and community building.</p>
<div style={{...cd(),marginBottom:20,borderTop:`3px solid ${C.pri}`}}><h3 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:600,marginBottom:6}}>The Three Legs of Any Policy Job</h3><p style={{fontSize:13,color:C.mid,lineHeight:1.65,marginBottom:14}}>Every policy role has three dimensions. The combinations are nearly infinite, which is why the field feels incoherent from the outside.</p>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:12}}>{[{t:"Space (Where)",d:"Think tank, govt, consulting, NGO, corporate, multilateral, philanthropy, legal, social enterprise, academia, political strategy, media",c:C.pri},{t:"Vertical (Which Sector)",d:"Health, education, climate, digital, urban, gender, finance, trade, governance, rural, defence, water, labour...",c:C.coral},{t:"Function (What You Do)",d:"Research, advocacy, programme management, regulatory, communications, M&E, govt relations, strategy, training, design...",c:C.navy}].map((l,i)=><div key={i} style={{background:C.warm,borderRadius:12,padding:14,borderTop:`3px solid ${l.c}`}}><div style={{fontSize:13,fontWeight:700,color:l.c,marginBottom:6}}>{l.t}</div><div style={{fontSize:12,color:C.mid,lineHeight:1.6}}>{l.d}</div></div>)}</div></div>
{PR.map((p,i)=>{const pc=[C.pri,C.coral,C.navy,C.plum,C.amber,C.emerald][i];return(<div key={i} style={{...cd(),marginBottom:16,borderLeft:`4px solid ${pc}`}}><div style={{position:"absolute",top:10,right:18,fontFamily:"'Fraunces',serif",fontSize:52,fontWeight:700,color:`${pc}08`}}>{p.n}</div><div style={{fontSize:11,color:pc,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.08em"}}>Principle {p.n}</div><h3 style={{fontFamily:"'Fraunces',serif",fontSize:20,fontWeight:600,margin:"6px 0 12px"}}>{p.t}</h3><blockquote style={{padding:"10px 16px",borderLeft:`3px solid ${pc}30`,background:`${pc}05`,borderRadius:"0 10px 10px 0",marginBottom:12}}><p style={{fontSize:14,color:C.mid,fontFamily:"'Fraunces',serif",fontStyle:"italic",lineHeight:1.6}}>"{p.q}"</p></blockquote><p style={{fontSize:13.5,color:C.mid,lineHeight:1.7}}>{p.d}</p></div>);})}
<div style={{...cd(),marginTop:20,borderTop:`3px solid ${C.emerald}`}}><h3 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:600,marginBottom:14}}>Why Policy Careers Are Exploding in India</h3>
{[{ph:"2000–2015",dr:"Rights-based legislation wave",dt:"RTI, MGNREGA, RTE, Food Security Act, Jan Lokpal, mandatory CSR (2013).",c:C.pri},{ph:"2015–2020",dr:"Regulatory complexity explosion",dt:"India crossing $1,500–2,000 GDP/capita. Startups, GST, bankruptcy code. States competing.",c:C.coral},{ph:"2020–present",dr:"Geopolitical + Climate + Digital",dt:"China decoupling, semiconductor policy, Net Zero 2070, AI governance, DPDP Act.",c:C.navy}].map((it,i)=><div key={i} style={{display:"flex",gap:14,alignItems:"flex-start",marginBottom:14,padding:"12px 14px",background:C.warm,borderRadius:10,borderLeft:`3px solid ${it.c}`}}><div style={{fontSize:12,fontWeight:700,color:it.c,minWidth:80}}>{it.ph}</div><div><div style={{fontSize:14,fontWeight:600,color:C.text,marginBottom:2}}>{it.dr}</div><div style={{fontSize:12.5,color:C.mid,lineHeight:1.6}}>{it.dt}</div></div></div>)}</div>
<PPICta/></div>}

</main>

<footer style={{borderTop:`1px solid ${C.border}`,padding:"20px 24px",background:"#FEFDFB"}}><div style={{maxWidth:980,margin:"0 auto",display:"flex",flexDirection:"column",alignItems:"center",gap:10}}><div style={{display:"flex",alignItems:"center",gap:8}}><PPILogo size={20}/><span style={{fontSize:13,fontWeight:600,color:C.mid}}>Public Policy India</span></div>
<div style={{fontSize:11,color:C.lt,textAlign:"center",lineHeight:1.6}}><a href="https://publicpolicyindia.com" target="_blank" rel="noopener noreferrer" style={{color:C.pri,textDecoration:"none",fontWeight:500}}>publicpolicyindia.com</a>{" · "}<a href="https://newsletter.publicpolicyindia.com" target="_blank" rel="noopener noreferrer" style={{color:C.pri,textDecoration:"none",fontWeight:500}}>Newsletter</a>{" · "}<a href="https://www.linkedin.com/company/public-policy-india/" target="_blank" rel="noopener noreferrer" style={{color:C.pri,textDecoration:"none",fontWeight:500}}>LinkedIn</a></div>
<div style={{fontSize:10,color:C.faint,textAlign:"center",lineHeight:1.5,maxWidth:600}}>All salary figures are approximate ranges based on available data from institutional placement reports, Glassdoor India, and industry estimates. Individual compensation varies by organisation, location, and experience.</div></div></footer>
</div>);}
